# Generated by Django 3.0.6 on 2020-05-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityCode', models.CharField(max_length=120, null=True)),
                ('cityName', models.CharField(max_length=120, null=True)),
                ('latitude', models.CharField(max_length=120, null=True)),
                ('longitude', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(max_length=120, null=True)),
                ('countryName', models.CharField(max_length=120, null=True)),
                ('englishName', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('yearOfExperience', models.CharField(max_length=120, null=True)),
                ('educationalSubstitution', models.BooleanField(default=False)),
                ('sexuality', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('fromAge', models.SmallIntegerField(null=True)),
                ('toAge', models.SmallIntegerField(null=True)),
                ('internship', models.BooleanField(default=False)),
                ('vision', models.CharField(max_length=120, null=True)),
                ('mbti', models.CharField(max_length=120, null=True)),
                ('revisionDate', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeTypeCode', models.CharField(max_length=120)),
                ('placeTypeName', models.CharField(max_length=120)),
                ('finishedGoodProductAccountCode', models.CharField(max_length=120)),
                ('rawMaterialAccountCode', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceCode', models.CharField(max_length=120, null=True)),
                ('provinceName', models.CharField(max_length=120, null=True)),
                ('latitude', models.CharField(max_length=120, null=True)),
                ('longitude', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileNumber', models.CharField(max_length=120, null=True)),
                ('cardNumber', models.CharField(max_length=120, null=True)),
                ('code', models.CharField(max_length=120, null=True)),
                ('firstName', models.CharField(max_length=120, null=True)),
                ('lastName', models.CharField(max_length=120, null=True)),
                ('fatherName', models.CharField(max_length=120, null=True)),
                ('nationalCode', models.CharField(max_length=120, null=True)),
                ('birthCertificateNumber', models.CharField(max_length=120, null=True)),
                ('issueDate', models.CharField(max_length=120, null=True)),
                ('birthDate', models.CharField(max_length=120, null=True)),
                ('deathDate', models.CharField(max_length=120, null=True)),
                ('marriageDate', models.CharField(max_length=120, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('email', models.CharField(max_length=120, null=True)),
                ('getEmail', models.BooleanField(default=False)),
                ('getSMS', models.BooleanField(default=False)),
                ('nfc', models.CharField(max_length=120, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Country')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Job')),
                ('marriageStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.MarriageStatus')),
                ('militaryService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.MilitaryService')),
                ('personType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.PersonType')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Religion')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.JobGroup'),
        ),
        migrations.AddField(
            model_name='job',
            name='placeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.PlaceType'),
        ),
        migrations.AddField(
            model_name='job',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Post'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Province'),
        ),
    ]
