# Generated by Django 3.0.6 on 2020-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontype',
            name='type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
