# Generated by Django 3.0.6 on 2020-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileNumber', models.CharField(max_length=120)),
                ('cardNumber', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('fatherName', models.CharField(max_length=120)),
                ('nationalCode', models.CharField(max_length=120)),
                ('birthCertificateNumber', models.CharField(max_length=120)),
                ('issueDate', models.CharField(max_length=120)),
                ('birthDate', models.CharField(max_length=120)),
                ('deathDate', models.CharField(max_length=120)),
                ('marriageDate', models.CharField(max_length=120)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('getEmail', models.BooleanField(default=False)),
                ('getSMS', models.BooleanField(default=False)),
                ('nfc', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.PositiveSmallIntegerField(blank=True)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
