# Generated by Django 3.0.6 on 2020-05-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityCode', models.CharField(max_length=120, null=True)),
                ('cityName', models.CharField(max_length=120, null=True)),
                ('latitude', models.CharField(max_length=120, null=True)),
                ('longitude', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=120, null=True)),
                ('CountryName', models.CharField(max_length=120, null=True)),
                ('EnglishName', models.CharField(max_length=120, null=True)),
                ('Explanation', models.CharField(max_length=120, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('IsSent', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=120, null=True)),
                ('Name', models.CharField(max_length=120, null=True)),
                ('YearOfExperience', models.CharField(max_length=120, null=True)),
                ('EducationalSubstitution', models.BooleanField(default=False)),
                ('Sexuality', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('FromAge', models.SmallIntegerField(max_length=120, null=True)),
                ('ToAge', models.SmallIntegerField(max_length=120, null=True)),
                ('Internship', models.BooleanField(default=False)),
                ('Vision', models.CharField(max_length=120, null=True)),
                ('mbti', models.CharField(max_length=120, null=True)),
                ('RevisionDate', models.CharField(max_length=120, null=True)),
                ('Explanation', models.CharField(max_length=120, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('IsSent', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=120, null=True)),
                ('Name', models.CharField(max_length=120, null=True)),
                ('Explanation', models.CharField(max_length=120, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('IsSent', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=120, null=True)),
                ('Name', models.CharField(max_length=120, null=True)),
                ('Explanation', models.CharField(max_length=120, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('IsSent', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=120)),
                ('Explanation', models.CharField(max_length=120)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('IsSent', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='birthCertificateNumber',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthDate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cardNumber',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='deathDate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='explanation',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fatherName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fileNumber',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='issueDate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='marriageDate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationalCode',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nfc',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='Country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='MarriageStatus',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='web.MarriageStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='MilitaryService',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.MilitaryService'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Religion',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='web.Religion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='personType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.PersonType'),
            preserve_default=False,
        ),
    ]
