# Generated by Django 3.0.6 on 2020-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200510_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='FromAge',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ToAge',
            field=models.SmallIntegerField(null=True),
        ),
    ]
