# Generated by Django 3.0.6 on 2020-05-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200510_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeTypeCode', models.CharField(max_length=120)),
                ('placeTypeName', models.CharField(max_length=120)),
                ('finishedGoodProductAccountCode', models.CharField(max_length=120)),
                ('rawMaterialAccountCode', models.CharField(max_length=120)),
                ('explanation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.JobGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='placeType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.PlaceType'),
            preserve_default=False,
        ),
    ]
