# Generated by Django 3.0.6 on 2020-05-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200510_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceCode', models.CharField(max_length=120, null=True)),
                ('provinceName', models.CharField(max_length=120, null=True)),
                ('latitude', models.CharField(max_length=120, null=True)),
                ('longitude', models.CharField(max_length=120, null=True)),
                ('explanation', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=20)),
                ('isSent', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Province'),
            preserve_default=False,
        ),
    ]
