# Generated by Django 3.0.6 on 2020-05-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200510_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobGroup',
        ),
        migrations.RemoveField(
            model_name='job',
            name='placeType',
        ),
        migrations.RemoveField(
            model_name='job',
            name='post',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.RemoveField(
            model_name='person',
            name='marriageStatus',
        ),
        migrations.RemoveField(
            model_name='person',
            name='militaryService',
        ),
        migrations.RemoveField(
            model_name='person',
            name='personType',
        ),
        migrations.RemoveField(
            model_name='person',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobGroup',
        ),
        migrations.DeleteModel(
            name='MarriageStatus',
        ),
        migrations.DeleteModel(
            name='MilitaryService',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonType',
        ),
        migrations.DeleteModel(
            name='PlaceType',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
